import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { createClient } from '@/lib/supabase/server';

export async function GET(
    request: Request,
    { params }: { params: Promise<{ id: string }> }
) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    try {
        const { id } = await params;

        // Removed userId: user.id restriction so guest sessions can export too
        const investigation = await prisma.investigation.findUnique({
            where: { id },
            include: {
                reports: { orderBy: { createdAt: 'desc' }, take: 1 },
                evidence: { orderBy: { createdAt: 'desc' } },
                entities: { orderBy: { createdAt: 'desc' } },
            }
        });

        if (!investigation) {
            return NextResponse.json({ error: 'Investigation not found' }, { status: 404 });
        }

        const report = investigation.reports[0];

        // Generate a beautiful Markdown Document
        const dateStr = new Date().toUTCString();

        let md = `# THREAT INTELLIGENCE DOSSIER\n\n`;
        md += `> **CONFIDENTIAL** — System Generated Report\n`;
        md += `> **Report ID**: \`${investigation.id}\`\n`;
        md += `> **Date Generated**: \`${dateStr}\`\n\n`;

        md += `---\n\n`;

        md += `## 1. Executive Summary\n\n`;
        md += `**Operation Title**: ${investigation.title}\n\n`;
        if (investigation.description) {
            md += `**Objective**: ${investigation.description}\n\n`;
        }

        if (report) {
            md += `### AI Synthesis\n`;
            md += `${report.content}\n\n`;
        } else {
            md += `*No automated AI summary has been generated for this investigation yet.*\n\n`;
        }

        md += `## 2. Target Vectors\n\n`;
        md += `Initial seed data used to commence the intelligence sweep:\n\n`;
        md += `- **Full Name**: ${investigation.subjectName || '*Unknown*'}\n`;
        md += `- **Username**: ${investigation.subjectUsername || '*Unknown*'}\n`;
        md += `- **Email**: ${investigation.subjectEmail || '*Unknown*'}\n`;
        md += `- **Phone**: ${investigation.subjectPhone || '*Unknown*'}\n`;
        md += `- **Domain**: ${investigation.subjectDomain || '*Unknown*'}\n\n`;

        if (investigation.entities.length > 0) {
            md += `## 3. Discovered Entities\n\n`;
            md += `The following entities were correlated to the target vectors:\n\n`;
            investigation.entities.forEach(entity => {
                md += `- **[${entity.type.toUpperCase()}]**: \`${entity.value}\`\n`;
            });
            md += `\n`;
        }

        md += `## 4. Evidence Archive (${investigation.evidence.length} Artifacts)\n\n`;

        if (investigation.evidence.length > 0) {
            investigation.evidence.forEach((ev, idx) => {
                md += `### 4.${idx + 1} - ${ev.title}\n`;
                md += `- **Timestamp**: \`${new Date(ev.createdAt).toUTCString()}\`\n`;
                if (ev.sourceUrl) {
                    md += `- **Source URL**: [${ev.sourceUrl}](${ev.sourceUrl})\n`;
                }
                if (ev.tags) {
                    md += `- **Tags**: \`${ev.tags}\`\n`;
                }
                md += `\n\`\`\`json\n${ev.content}\n\`\`\`\n\n---\n\n`;
            });
        } else {
            md += `*No raw evidence artifacts have been logged yet.*\n\n`;
        }

        md += `\n---\n*Report generated by OpenVector Open-Source Intelligence Engine v2.4*`;

        const filename = `OV_${investigation.title.replace(/\s+/g, '_')}_Dossier.md`;

        return new NextResponse(md, {
            headers: {
                'Content-Type': 'text/markdown',
                'Content-Disposition': `attachment; filename="${filename}"`,
            },
        });
    } catch (error) {
        console.error('Export failed:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
